ROOT: benchmark_results 
r_env : scib-R4.1
py_env : scib-pipeline-R4.1

unintegrated_metrics: true

FEATURE_SELECTION:
  hvg: 2000
  full_feature: 0

SCALING:
  - unscaled
  - scaled

METHODS:
# python methods
  scanorama:
    output_type:
      - embed
      - full
  scvi:
    no_scale: true
    output_type: embed
# R methods
  seurat:
    R: true
    output_type: full
  seuratrpca:
      R: true
      output_type: full
  fastmnn:
    R: true
    output_type:
      - embed
      - full
  harmony:
    R: true
    output_type: embed
  coralysis:
    R: true
    output_type: embed

DATA_SCENARIOS:
  pancreas:
    batch_key: tech
    label_key: celltype
    organism: human
    assay: expression
    file: data/datasets/human_pancreas_norm_complexBatch.h5ad
  lung_atlas:
    batch_key: batch
    label_key: cell_type
    organism: human
    assay: expression
    file: data/datasets/Lung_atlas_public.h5ad
  immune_cell_hum:
    batch_key: batch
    label_key: final_annotation
    organism: human
    assay: expression
    file: data/datasets/Immune_ALL_human.h5ad
  immune_cell_hum_mou:
    batch_key: batch
    label_key: final_annotation
    organism: human
    assay: expression
    file: data/datasets/Immune_ALL_hum_mou.h5ad
  simulations_1_1:
    batch_key: Batch
    label_key: Group
    organism: human
    assay: simulation
    file: data/datasets/sim1_1_norm.h5ad
  simulations_2:
    batch_key: SubBatch
    label_key: Group
    organism: human
    assay: simulation
    file: data/datasets/sim2_norm.h5ad
  ifnb: 
    batch_key: stim
    label_key: seurat_annotations
    organism: human
    assay: expression
    file: data/datasets/ifnb.h5ad

